# **Using NumPy**

Once you've installed NumPy you can import it as a library:

In [ ]:
import numpy as np

Numpy has many built-in functions and capabilities. We won't cover them all but instead we will focus on some of the most important aspects of Numpy: vectors,arrays,matrices, and number generation. Let's start by discussing arrays.

# Numpy Arrays

NumPy arrays are the main way we will use Numpy throughout the course. Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d (but you should note a matrix can still have only one row or one column).

Let's begin our introduction by exploring how to create NumPy arrays.

## Creating NumPy Arrays

### From a Python List

We can create an array by directly converting a list or list of lists:

In [ ]:
a = [1,2,3,4,5]
type(a)

list

In [ ]:
arr = np.array(a)
arr

array([1, 2, 3, 4, 5])

In [ ]:
#in list we can add different datatypes , strings, numeric data or float data
#but in array if we use one element as string it will convert it to unicodes and will convert every element to strings
b = [1,"2",3,4,5]
barr = np.array(b)
barr.dtype
barr

array(['1', '2', '3', '4', '5'], dtype='<U21')

Lets create a matrix using list

In [ ]:
#matrix means creating something in 2 dimensional space
a = [[1,2,3],[4,5,6],[7,8,9]]
arr = np.array(a)
arr
#if we will print a all elements will be printed in straight line but if we convert it into array then it will become 2 dimensional

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Now lets see how matlix looks like using numpy arrays

In [ ]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Built-in Methods

there are lots of build in methods to create an array lets create some and see

np.zeros(), np.ones(), np.full()

np.arange(), np.linspace()

np.eye()

### **np.zeros()**

In [ ]:
#you will create an array of zeros with np.zeros()
# one dimensional
arr = np.zeros(10)
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
# two dimensional
barr = np.zeros([5,6])
barr

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

**np.ones()**

In [ ]:
#similar working as np.zeros() the only change is the array created is of one
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
np.ones([4,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

**np.full()**

In [ ]:
np.full([5,5],7)
# 5 rows and 5 columns filled with number 7

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

**np.arrage()**

In [ ]:
#it works like range func , give starting and end point
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

**np.linspace()**

In [ ]:
# it arranges elements of a range in equal or linear space
#elements between 1 and 10 will be equally divided into 5
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

**np.eye()**

In [ ]:
#eye is used to form identity matrix (1 in diagonal elements)
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

**np.random()**

In [ ]:
#will create an array with random values
np.random.rand(5,5)
#values will always be between 0 and 1

array([[0.46749768, 0.64972015, 0.41790684, 0.93540299, 0.77564192],
       [0.47851799, 0.53932616, 0.50634526, 0.56981428, 0.8926484 ],
       [0.53423684, 0.25309648, 0.64632322, 0.46924905, 0.00908242],
       [0.54133684, 0.23947819, 0.27439728, 0.36629855, 0.80137648],
       [0.01838546, 0.69893083, 0.75010391, 0.91726247, 0.65240783]])

In [ ]:
#how to create random integers
#randint - random integer
#give range of number 1 to 10 and then size of array 3 (1D array) or [3,3] (2D array)
np.random.randint(1,10,[3,3])

array([[8, 2, 7],
       [6, 4, 7],
       [7, 3, 9]])

In [ ]:
arr = np.random.randn(2,4)
#values between -3 and +3
arr

array([[-0.04226794,  1.32694128, -0.3482597 ,  0.81588152],
       [-0.73196357,  0.51534276, -0.60244727, -1.29265854]])

arange → step-based values

linspace → fixed number of values

eye → identity matrix

rand → random floats (0–1)

randint → random integers in a range

randn → random values from bell curve distribution