**General Questions**

In [61]:
import numpy as np

# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

In [62]:
#Get the shape of the matrix.
data.shape

(5, 3)

In [63]:
#Find the average age of students.
print(np.mean(data[:,0]))

18.4


In [64]:
#Extract Math marks of all students.
print(data[:,1])

[85 92 76 65 90]


In [65]:
#Find the highest Science mark.
print(np.max(data[:,2]))

95


In [66]:
#Get details of the student who scored more than 90 in Math.
data[data[:,1]>90]

array([[19, 92, 88]])

In [67]:
#Increase Math marks of all students by 5.
data[:,1] +=5
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70, 70],
       [20, 95, 85]])

In [68]:
#Find how many students are younger than 19.
len(data[data[:,0]<19])

3

In [69]:
#Calculate the average marks in each subject (column-wise mean).
print("maths",np.mean(data[:,1]))
print("science",np.mean(data[:,2]))


maths 86.6
science 83.2


In [70]:
#Get data of students who scored at least 80 in both subjects.
data[(data[:,1]>=80) & (data[:,2]>=80)]

array([[19, 97, 88],
       [17, 81, 95],
       [20, 95, 85]])

In [71]:
#Replace all Science marks < 75 with 0.
data[:,2][data[:,2]<75] = 0
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70,  0],
       [20, 95, 85]])